name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@main
      with: 
          submodules: 'true'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true

    - name: 'Build'
      run: |
        msbuild virtio-win.sln -p:Configuration:Release -p:Platform:ARM64
