name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@main
      with: 
          submodules: 'true'

    - name: 'Build'
      run: |
        build_AllNoSdv
        wdkver -list
